Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 16/02/2019
Var
// Seção de Declarações das variáveis 

nome:caractere
idade:inteiro
altura:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

nome <-"Yago"
idade <-15
altura <- 1.74

escreval (nome)
escreval (idade)
escreval (altura)

Fimalgoritmo